version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./players.json:/usr/src/app/players.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge