prometheus:
    image: prom/prometheus:latest
    ports:
        - "9090:9090"
    volumes:
        - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        - prometheus_data:/prometheus
    networks:
        - app-network